= What is https://stken2050.github.io/timeline-monad/[timeline-monad]?
ifndef::stem[:stem: latexmath]
ifndef::imagesdir[:imagesdir: ./img/]
ifndef::source-highlighter[:source-highlighter: highlightjs]
ifndef::highlightjs-theme:[:highlightjs-theme: solarized-dark]

1. *timeline-monad* is a JavaScript(ES6+) module of a minimal (super simple) implementation for __Functional Reactive Programming(FPP)__. The module provides *first class reactive values _'over time'_* .

2. *timeline-monad* is robust for _function composition_
because it has a https://ncatlab.org/nlab/show/monad[_monad_] structure.

3. *timeline-monad*'s https://github.com/stken2050/timeline-monad/blob/master/dist/esm/timeline-monad.js[source code] is **less than 40 lines**(ESModule version, the comment lines excluded).

4. The code is https://github.com/stken2050/timeline-monad/tree/master/test-jest[heavily tested] including to https://github.com/stken2050/timeline-monad/blob/master/test-jest/monad.test.js[satisfy monad laws]. 

[TIP]
.Monad?
====
Although **timeline-monad** has a monad structure, for **unlimitedjs** applications, we don't have to dive into monad world.

For this purpose, we use **timeline-monad** just as reactive mapping of __timeline__.
==== 


== Timeline

In **timeline-monad**, the first class reactive values 'over time' is called __**timeline**__.

Many FRP libraries call it __stream__ etc.. The problem of the naming: __stream__ is it reminds us something dynamic, mutable, and the fundamental concept of FRP is to view the world immutable, so the value is called __timeline__ here.

=== Hello timeline
++++
<iframe height="265" style="width: 100%;" scrolling="no" title="Hello Timeline" src="https://codepen.io/stken2050/embed/ZwOaEr/?height=265&theme-id=36003&default-tab=js,result" frameborder="no" allowtransparency="true" allowfullscreen="true">
  See the Pen <a href='https://codepen.io/stken2050/pen/ZwOaEr/'>Hello Timeline</a> by Ken OKABE
  (<a href='https://codepen.io/stken2050'>@stken2050</a>) on <a href='https://codepen.io'>CodePen</a>.
</iframe>
++++

=== Equation

[stem]
++++
timelineB = timelineA \times 2
++++
 
`timelineB` is declared to be _always_ synchronized with `timelineA`, and the equation is guaranteed to be satisfied.

`timelineB` depends (relies) on `timelineA`, and when `timelineA` is updated, `timelineB` is also automatically updated.

To describe this relation, the code is below:

[source,js]
.timeline equation sync
----
const timelineA = T(); <1>
const timelineB = timelineA
            .sync(a => a * 2); <2>
const timeline = timelineB
          .sync(b => console.log(b)); <3>
  
setTimeout(()=>
      (timelineA.now = 1), 100);  <4>
  
setTimeout(()=>
      (timelineA.now = 5), 200);  <5>
----

<1> Declare empty `timelineA`
<2> Declare `timelineB` that is synchronized with `timelineA` that satisfies the given function
<3> On `timelineB` updates, `console.log` the value
<4> later, the value of `timelineA` becomes `1`
<5> later, the value of `timelineA` becomes `5`

++++
<iframe height="447" style="width: 100%;" scrolling="no" title="Hello Timeline Sync" src="https://codepen.io/stken2050/embed/mvpaER/?height=447&theme-id=36003&default-tab=js,result" frameborder="no" allowtransparency="true" allowfullscreen="true">
  See the Pen <a href='https://codepen.io/stken2050/pen/mvpaER/'>Hello Timeline Sync</a> by Ken OKABE
  (<a href='https://codepen.io/stken2050'>@stken2050</a>) on <a href='https://codepen.io'>CodePen</a>.
</iframe>
++++

=== Timer timeline
++++
<iframe height="373" style="width: 100%;" scrolling="no" title="Hello Timeline timer" src="https://codepen.io/stken2050/embed/daNXja/?height=373&theme-id=36003&default-tab=js,result" frameborder="no" allowtransparency="true" allowfullscreen="true">
  See the Pen <a href='https://codepen.io/stken2050/pen/daNXja/'>Hello Timeline timer</a> by Ken OKABE
  (<a href='https://codepen.io/stken2050'>@stken2050</a>) on <a href='https://codepen.io'>CodePen</a>.
</iframe>
++++

=== Canvas

++++
<iframe height="550" style="width: 100%;" scrolling="no" title="unlimitedjs_canvas" src="https://codepen.io/stken2050/embed/jdmeYK/?height=550&theme-id=36003&default-tab=js,result" frameborder="no" allowtransparency="true" allowfullscreen="true">
  See the Pen <a href='https://codepen.io/stken2050/pen/jdmeYK/'>unlimitedjs_canvas</a> by Ken OKABE
  (<a href='https://codepen.io/stken2050'>@stken2050</a>) on <a href='https://codepen.io'>CodePen</a>.
</iframe>
++++

[source,js]
.timeline Canvas
----
import { T } from "../../node_modules/timeline-monad/dist/esm/timeline-monad.js";

const canvas = document.getElementById('canvas1'); <1>

const pointerTL = T(self => {    <2>
  canvas.onmousemove = e =>
    self.now = { x: e.clientX, y: e.clientY };
});

const drawTL = T(self => {   <3>
  const ctx = canvas.getContext('2d');
  const timeline = self.sync(pointer => {
    ctx.clearRect(0, 0, canvas.width, canvas.height);
    ctx.beginPath();
    ctx.arc(pointer.x - 10, pointer.y - 10, 10, 0, Math.PI * 2, true);
    ctx.fillStyle = "red";
    ctx.fill();
  });
});

const timeline = pointerTL.sync(pointer =>    <4>
  drawTL.now = pointer
);
----

<1> canvas DOM node
<2> INPUT: __timeline__ of mouse pointer coordinate
<3> OUTPUT: __timeline__ of canvas drawing
<4> INPUT(pointerTL) is synchronized with OUTPUT(drawTL)

=== Virtual DOM (Superfine)

++++
<iframe height="654" style="width: 100%;" scrolling="no" title="unlimitedjs_vdom" src="https://codepen.io/stken2050/embed/xMdyjx/?height=654&theme-id=36003&default-tab=js,result" frameborder="no" allowtransparency="true" allowfullscreen="true">
  See the Pen <a href='https://codepen.io/stken2050/pen/xMdyjx/'>unlimitedjs_vdom</a> by Ken OKABE
  (<a href='https://codepen.io/stken2050'>@stken2050</a>) on <a href='https://codepen.io'>CodePen</a>.
</iframe>
++++

[source,js]
.timeline virtualDOM
----
import { T, world } from "https://unpkg.com/timeline-monad@2.0.0/code/dist/timeline-monad.js";　

const _canvas = document.getElementById('canvas1');
const canvas = (_canvas == null)   <1>
  ? {} as HTMLCanvasElement
  : _canvas as HTMLCanvasElement;

const pointerTL = T(self => {  <2>
  canvas.onmousemove = e =>
    self.now = { x: e.clientX, y: e.clientY };
});

const drawTL = T(self => {  <3>
  const _ctx = canvas.getContext('2d');
  const ctx = (_ctx == null)
    ? {} as CanvasRenderingContext2D
    : _ctx;
  const timeline = self.sync(pointer => {
    ctx.clearRect(0, 0, canvas.width, canvas.height);
    ctx.beginPath();
    ctx.arc(pointer.x - 10, pointer.y - 10, 10, 0, Math.PI * 2, true);
    ctx.fillStyle = "red";
    ctx.fill();
  });
});

const timeline = pointerTL.sync(pointer =>  <4>
  drawTL.now = pointer
);

world.now = pointerTL;
world.now = drawTL;
----

<1> real DOM node (named as `canvas`)
<2> INPUT: __timeline__ of mouse pointer coordinate : __same code of **timeline Canvas**__ 
<3> OUTPUT: __timeline__ of virtualDOM drawing(rendering)
<4> INPUT(pointerTL) is synchronized with OUTPUT(drawTL)  : __same code of **timeline Canvas**__

== Read more on https://stken2050.github.io/timeline-monad/[timeline-monad Docs & Tutorial]
