= What is timeline-monad?
ifndef::stem[:stem: latexmath]
ifndef::imagesdir[:imagesdir: ./img/]
ifndef::source-highlighter[:source-highlighter: highlightjs]
ifndef::highlightjs-theme:[:highlightjs-theme: solarized-dark]

1. *timeline-monad* is a JavaScript(ES6+) module of a minimal (super simple) implementation for __Functional Reactive Programming(FPP)__. The module provides *first class reactive values _'over time'_* .

2. *timeline-monad* is robust for _function composition_
because it has a https://ncatlab.org/nlab/show/monad[_monad_] structure.

3. *timeline-monad*'s https://github.com/stken2050/timeline-monad/blob/master/dist/esm/timeline-monad.js[source code] is **less than 40 lines**(ESModule version, the comment lines excluded).

4. The code is https://github.com/stken2050/timeline-monad/tree/master/test-jest[heavily tested] including to https://github.com/stken2050/timeline-monad/blob/master/test-jest/monad.test.js[satisfy monad laws]. 


Although it has a monad structure, for unlimitedjs applications, we don't have to dive into monad world.

For this purpose, we use `timeline-monad` just as reactive mapping of timelines.

== Timeline

In timeline-monad, the first class reactive values 'over time' is called __**timeline**__.

Many FRP libraries call it **stream** etc.. The problem of the naming: stream is it reminds us something dynamic, mutable, and the fundamental concept of FRP is to view the world immutable, so the value is called __**timeline**__ here.

=== Hello timeline
++++
<iframe height="265" style="width: 100%;" scrolling="no" title="Hello Timeline" src="//codepen.io/stken2050/embed/ZwOaEr/?height=265&theme-id=0&default-tab=js,result" frameborder="no" allowtransparency="true" allowfullscreen="true">
  See the Pen <a href='https://codepen.io/stken2050/pen/ZwOaEr/'>Hello Timeline</a> by Ken OKABE
  (<a href='https://codepen.io/stken2050'>@stken2050</a>) on <a href='https://codepen.io'>CodePen</a>.
</iframe>
++++

=== Timer timeline
++++
<iframe height="373" style="width: 100%;" scrolling="no" title="Hello Timeline timer" src="//codepen.io/stken2050/embed/daNXja/?height=373&theme-id=0&default-tab=js,result" frameborder="no" allowtransparency="true" allowfullscreen="true">
  See the Pen <a href='https://codepen.io/stken2050/pen/daNXja/'>Hello Timeline timer</a> by Ken OKABE
  (<a href='https://codepen.io/stken2050'>@stken2050</a>) on <a href='https://codepen.io'>CodePen</a>.
</iframe>
++++

=== Canvas

++++
<iframe height="550" style="width: 100%;" scrolling="no" title="unlimitedjs_canvas" src="//codepen.io/stken2050/embed/jdmeYK/?height=550&theme-id=36003&default-tab=js,result" frameborder="no" allowtransparency="true" allowfullscreen="true">
  See the Pen <a href='https://codepen.io/stken2050/pen/jdmeYK/'>unlimitedjs_canvas</a> by Ken OKABE
  (<a href='https://codepen.io/stken2050'>@stken2050</a>) on <a href='https://codepen.io'>CodePen</a>.
</iframe>
++++

[source,js]
.timeline Canvas
----
import { T } from "../../node_modules/timeline-monad/dist/esm/timeline-monad.js";

const _canvas = document.getElementById('canvas1');
const canvas = (_canvas == null)
  ? {} as HTMLCanvasElement
  : _canvas as HTMLCanvasElement;

const pointerTL = T(self => {
  canvas.onmousemove = e =>
    self.now = { x: e.clientX, y: e.clientY };
});

const drawTL = T(self => {
  const _ctx = canvas.getContext('2d');
  const ctx = (_ctx == null)
    ? {} as CanvasRenderingContext2D
    : _ctx;
  const timeline = self.sync(pointer => {
    ctx.clearRect(0, 0, canvas.width, canvas.height);
    ctx.beginPath();
    ctx.arc(pointer.x - 10, pointer.y - 10, 10, 0, Math.PI * 2, true);
    ctx.fillStyle = "red";
    ctx.fill();
  });
});

const timeline = pointerTL.sync(pointer =>
  drawTL.now = pointer
);
----

<1> virtual DOM node
<2> The only API `patch` returns next "last" node.
<3> last (old) virtual DOM node
<4> next (new) virtual DOM node
<5> Real DOM Container to render the virtual DOM

=== Virtual DOM (Superfine)

++++
<iframe height="654" style="width: 100%;" scrolling="no" title="unlimitedjs_vdom" src="//codepen.io/stken2050/embed/xMdyjx/?height=654&theme-id=36003&default-tab=js,result" frameborder="no" allowtransparency="true" allowfullscreen="true">
  See the Pen <a href='https://codepen.io/stken2050/pen/xMdyjx/'>unlimitedjs_vdom</a> by Ken OKABE
  (<a href='https://codepen.io/stken2050'>@stken2050</a>) on <a href='https://codepen.io'>CodePen</a>.
</iframe>
++++

[source,js]
.timeline virtualDOM
----
import { T } from "../../node_modules/timeline-monad/dist/esm/timeline-monad.js";
import { h, patch } from "../../node_modules/superfine/src/index.js";

const _canvas = document.getElementById('vdom1');
const canvas = (_canvas == null)
  ? {} as HTMLElement
  : _canvas as HTMLElement;

const pointerTL = T(self => {
  canvas.onmousemove = e =>
    self.now = { x: e.clientX, y: e.clientY };
});

const drawTL = T(self => {
  const topNodeTL = self.sync(pointer =>
    <div style={{
      "left": (pointer.x - 20) + "px",
      "top": (pointer.y - 20) + "px",
      "width": "20px",
      "height": "20px",
      "border-radius": "50%",
      "background-color": "red",
      "position": "relative"
    }}></div>
  );
  const viewNodeTL = topNodeTL.sync(topNode =>
    patch(viewNodeTL.now, topNode, canvas)
  );
});

const timeline = pointerTL.sync(pointer =>
  drawTL.now = pointer
); 
----

<1> virtual DOM node
<2> The only API `patch` returns next "last" node.
<3> last (old) virtual DOM node
<4> next (new) virtual DOM node
<5> Real DOM Container to render the virtual DOM

== Read more on https://stken2050.github.io/timeline-monad/[timeline-monad Docs & Tutorial]
