= unlimitedjs = superfine + timeline-monad
ifndef::stem[:stem: latexmath]
ifndef::imagesdir[:imagesdir: ./img/]
ifndef::source-highlighter[:source-highlighter: highlightjs]
ifndef::highlightjs-theme:[:highlightjs-theme: solarized-dark]

Another good news is we can also forget `patch` since unlimitedjs embeds `patch` into  a certain code pattern.

Although there are absolutely no rules or limitations, here is a very basic structure of unlimitedjs code.

[source,js]
.Hello world of unlimitedjs
----
import { T } from "timeline-monad";
import { h, patch } from "superfine";

  const topNodeTL = T(); <1>
  const viewNodeTL = topNodeTL.sync( <2>
    topNode => patch(viewNodeTL.now, topNode, document.body) <3>
  );

  const helloNode = <div>hello!</div>; <4>
  topNodeTL.now = helloNode; <5>
----

<1> Define `topNodeTL` as a **timeline(__first class reactive value 'over time'__)** of virtual DOM node: `topNode`
<2> Define `viewNodeTL` as a **timeline** of "last (old) node" that is *always synchronized with `topNodeTL`* <= `topNode` timeline
<3> `topNode` is the next (new) virtual DOM node
<4> virtual DOM node
<5> Define the latest "state" on the topNode timeline, which means **update**

In unlimitedjs(timeline) framework, if a value is mutable, then it's a timeline.

++++
<iframe height="345" style="width: 100%;" scrolling="no" title="Hello unlimitedjs" src="//codepen.io/stken2050/embed/yZpvQV/?height=345&theme-id=36003&default-tab=js,result" frameborder="no" allowtransparency="true" allowfullscreen="true">
  See the Pen <a href='https://codepen.io/stken2050/pen/yZpvQV/'>Hello unlimitedjs</a> by Ken OKABE
  (<a href='https://codepen.io/stken2050'>@stken2050</a>) on <a href='https://codepen.io'>CodePen</a>.
</iframe>
++++

== Mutable virtual DOM is easy

If we understand the idea of Hello world code of unlimitedjs, to write a mutable virtual DOM is pretty much straight forward.

No fancy rules, no restrictions. Just a plain JavaScript programming.

[source,js]
.Clock
----
import { T } from "timeline-monad";
import { h, patch } from "superfine";

  const topNodeTL = T(); <1>
  const viewNodeTL = topNodeTL.sync( <2> 
    topNode => patch(viewNodeTL.now, topNode, document.body) <3>
  );

  const f = () => { <4>
    const timeString = new Date().toLocaleTimeString(); <5>
    const clockNode = <div>{timeString}</div>; <6>
    topNodeTL.now = clockNode; <7>
  };
  setInterval(f, 1000); <8>
----

<1> same as Hello world
<2> same as Hello world
<3> same as Hello world
<4> `setInterval` function : `f`
<5> Obtain the current time strings
<6> `{timeString}` is a way to write variables inside of virtual DOM node in JSX
<7> Define the latest "state" on the topNode timeline, which means **update**
<8> `setInterval` triggers `f` every 1 second

++++
<iframe height="447" style="width: 100%;" scrolling="no" title="unlimitedjs clock" src="//codepen.io/stken2050/embed/WPdzrG/?height=447&theme-id=36003&default-tab=js,result" frameborder="no" allowtransparency="true" allowfullscreen="true">
  See the Pen <a href='https://codepen.io/stken2050/pen/WPdzrG/'>unlimitedjs clock</a> by Ken OKABE
  (<a href='https://codepen.io/stken2050'>@stken2050</a>) on <a href='https://codepen.io'>CodePen</a>.
</iframe>
++++

== SelfContained __timeline__ of virtual DOM

[source,js]
.SelfContained Clock
----
import { T } from "timeline-monad";
import { h, patch } from "superfine";

  const clockTL = T((self) => { <1>
    const f = () =>     <2>
      self.now = new Date().toLocaleTimeString(); <3>
    setInterval(f, 1000);    <4>
  });

  const clockNodeTL = clockTL.sync( <5>
    clock => (<div>{clock}</div>)
  );

  const topNodeTL = clockNodeTL;

  const viewNodeTL = topNodeTL.sync( <6>
    topNode => patch(viewNodeTL.now, topNode, document.body) 
  );
----

<1> SelfContained Clock __timeline__
<2> `setInterval` function : `f`
<3> Obtain the current time strings
<4> `setInterval` triggers `f` every 1 second
<5> `clockTL` is synchronized with the `clockNode` virtual DOM __timeline__
<6> virtual DOM rendering

++++
<iframe height="427" style="width: 100%;" scrolling="no" title="unlimitedjs self-contained clock" src="//codepen.io/stken2050/embed/daJmRE/?height=427&theme-id=36003&default-tab=js,result" frameborder="no" allowtransparency="true" allowfullscreen="true">
  See the Pen <a href='https://codepen.io/stken2050/pen/daJmRE/'>unlimitedjs self-contained clock</a> by Ken OKABE
  (<a href='https://codepen.io/stken2050'>@stken2050</a>) on <a href='https://codepen.io'>CodePen</a>.
</iframe>
++++

---

In the above case, `clockTL` is a global __timeline__, and it's also possible to define it as a local __timeline__ as below.

[source,js]
.SelfContained Counter2
----
import { T } from "timeline-monad";
import { h, patch } from "superfine";

  const clockNodeTL = T(self => {
    const clockTL = T((self) => { <1>
      const f = () =>
        self.now = new Date().toLocaleTimeString();
      setInterval(f, 1000);
    });
    const timeline = clockTL.sync(clock =>
      self.now = <div>{clock}</div> <2>
    );
  });

  const topNodeTL = clockNodeTL;

  const viewNodeTL = topNodeTL.sync(
    topNode => patch(viewNodeTL.now, topNode, document.body)
  );
----

<1> `clockTL` is a local __timeline__ contained in the global `clockNodeTL`
<2> `self` is the `clockNodeTL` itself and synchronized with `clockTL`

++++
<iframe height="551" style="width: 100%;" scrolling="no" title="unlimitedjs self-contained clock2" src="//codepen.io/stken2050/embed/bzaxzm/?height=551&theme-id=36003&default-tab=js,result" frameborder="no" allowtransparency="true" allowfullscreen="true">
  See the Pen <a href='https://codepen.io/stken2050/pen/bzaxzm/'>unlimitedjs self-contained clock2</a> by Ken OKABE
  (<a href='https://codepen.io/stken2050'>@stken2050</a>) on <a href='https://codepen.io'>CodePen</a>.
</iframe>
++++

---

[source,js]
.SelfContained Counter
----
import { T } from "timeline-monad";
import { h, patch } from "superfine";

  const counterNodeTL = T(self => { <1>
    const countTL = T(self => {  <2>
      const f = () => self.now = 0;  <3>
      setTimeout(f, 0); <4>
    }); 
    const timeline = countTL.sync(count =>  <5>
      self.now = (<div>
        <p>You clicked {count} times</p>
        <button onclick={() => countTL.now = count + 1}>
          Click me
        </button>
      </div>)
    );
  });

  const topNodeTL = counterNodeTL;

  const viewNodeTL = topNodeTL.sync(topNode => <6>
    patch(viewNodeTL.now, topNode, document.body)
  );
----

<1> SelfContained CounterNode __timeline__
<2> SelfContained Count __timeline__
<3> Initialize the count number
<4> setTimeout next tick after the whole declarations
<5> `countTL` is synchronized with the virtual DOM __timeline__
<6> virtual DOM rendering

++++
<iframe height="636" style="width: 100%;" scrolling="no" title="unlimitedjs self-contained counter" src="//codepen.io/stken2050/embed/MLrVPX/?height=636&theme-id=36003&default-tab=js,result" frameborder="no" allowtransparency="true" allowfullscreen="true">
  See the Pen <a href='https://codepen.io/stken2050/pen/MLrVPX/'>unlimitedjs self-contained counter</a> by Ken OKABE
  (<a href='https://codepen.io/stken2050'>@stken2050</a>) on <a href='https://codepen.io'>CodePen</a>.
</iframe>
++++