= unlimitedjs = superfine + timeline-monad
ifndef::stem[:stem: latexmath]
ifndef::imagesdir[:imagesdir: ./img/]
ifndef::source-highlighter[:source-highlighter: highlightjs]
ifndef::highlightjs-theme:[:highlightjs-theme: solarized-dark]

Another good news is we can also forget `patch` since unlimitedjs embeds `patch` into  a certain code pattern.

Although there are absolutely no rules or limitations, here is a very basic structure of unlimitedjs code.

[source,js]
.Hello world of unlimitedjs
----
import { T, world } from "timeline-monad";
import { h, patch } from "superfine";

  const topNodeTL = T(); <1>
  const viewNodeTL = topNodeTL.sync( <2>
    topNode => <3> 
     patch(document.getElementById("app"), helloNode  
    );
  );

  const helloNode = <div>hello!</div>; <4>
  topNodeTL.now = helloNode; <5>
----

<1> Define `topNodeTL` as a **timeline(__first class reactive value 'over time'__)** of virtual DOM node: `topNode`
<2> Define `viewNodeTL` as a **timeline** of "last (old) node" that is *always synchronized with `topNodeTL`* <= `topNode` timeline
<3> `topNode` is the next (new) virtual DOM node
<4> virtual DOM node
<5> Define the latest "state" on the topNode timeline, which means **update**

In unlimitedjs(timeline) framework, if a value is mutable, then it's a timeline.

++++
<iframe height="345" style="width: 100%;" scrolling="no" title="Hello unlimitedjs" src="https://codepen.io/stken2050/embed/yZpvQV/?height=345&theme-id=36003&default-tab=js,result" frameborder="no" allowtransparency="true" allowfullscreen="true">
  See the Pen <a href='https://codepen.io/stken2050/pen/yZpvQV/'>Hello unlimitedjs</a> by Ken OKABE
  (<a href='https://codepen.io/stken2050'>@stken2050</a>) on <a href='https://codepen.io'>CodePen</a>.
</iframe>
++++

== Mutable virtual DOM is easy

If we understand the idea of Hello world code of unlimitedjs, to write a mutable virtual DOM is pretty much straight forward.

No fancy rules, no restrictions. Just a plain JavaScript programming.

[source,js]
.Clock
----
import { T, world } from "timeline-monad";
import { h, patch } from "superfine";

  const newNodeTL = T(self =>  <1>
    self.sync(node => <2>
      patch(document.getElementById("app"), node) <3>
    )
  );

  world.now = newNodeTL;  <4>

  const f = () => {  <5>
    const timeString = new Date().toLocaleTimeString(); <6>
    const clockNode = <div>{timeString}</div>; <7>
    newNodeTL.now = clockNode; <8>
  };
  setInterval(f, 1000);  <9>
----

<1> self is `newNodeTL`
<2> define the behavior when self is updated
<3> superfine patch work
<4> Initialize  `newNodeTL`
<5> `setInterval` function : `f`
<6> Obtain the current time strings
<7> `{timeString}` is a way to write variables inside of virtual DOM node in JSX
<8> Define the latest "state" on the topNode timeline, which means **update**
<9> `setInterval` triggers `f` every 1 second

++++
<iframe height="447" style="width: 100%;" scrolling="no" title="unlimitedjs clock" src="https://codepen.io/stken2050/embed/WPdzrG/?height=447&theme-id=36003&default-tab=js,result" frameborder="no" allowtransparency="true" allowfullscreen="true">
  See the Pen <a href='https://codepen.io/stken2050/pen/WPdzrG/'>unlimitedjs clock</a> by Ken OKABE
  (<a href='https://codepen.io/stken2050'>@stken2050</a>) on <a href='https://codepen.io'>CodePen</a>.
</iframe>
++++
