= Compose __timeline__ of virtual DOM functionally
ifndef::stem[:stem: latexmath]
ifndef::imagesdir[:imagesdir: ./img/]
ifndef::source-highlighter[:source-highlighter: highlightjs]
ifndef::highlightjs-theme:[:highlightjs-theme: solarized-dark]

Everything mutable(as it seems in immutable universe) in unlimitedjs is __timeline__ including value and **virtualDOM node**.

Unlike https://reactjs.org/docs/components-and-props.html[React.Component], in unlimitedjs, a mutable virtualDOM node is abstracted simply as an **__timeline__ of virtualDOM node**.
 

One of the functional way is to define "merge" __timeline__ like this:

[source,js]
.merge __timeline__
----
  const mergeTL = (TLs => T(self =>
    TLs.map(TL => TL.sync(() =>
      self.now = TLs.map(TL => TL.now)
    ))
  ))([timelineA, timelineB]);
----

Here's how the `mergeTL` works:

++++
<iframe height="638" style="width: 100%;" scrolling="no" title="mirge Timeline test" src="https://codepen.io/stken2050/embed/damJZP/?height=638&theme-id=36003&default-tab=js,result" frameborder="no" allowtransparency="true" allowfullscreen="true">
  See the Pen <a href='https://codepen.io/stken2050/pen/damJZP/'>mirge Timeline test</a> by Ken OKABE
  (<a href='https://codepen.io/stken2050'>@stken2050</a>) on <a href='https://codepen.io'>CodePen</a>.
</iframe>
++++

---

With `mergeTL`, topNode __timeline__ can be defined as follow:

[source,js]
.topNode __timeline__
----
  const mergeTL = (TLs => T(self =>
    TLs.map(TL => TL.sync(() =>
      self.now = TLs.map(TL => TL.now)
    ))
  ))([clockNodeTL, counterNodeTL]);

  const topNodeTL = T(self =>
    mergeTL.sync(([clockNode, counterNode]) =>
      self.now = <div>
        <h3>{clockNode}</h3>
        {counterNode}
      </div>
    )
  );
----

The final code is:

[source,js]
.viewNode <- topNode <- (clockNode + counterNode)
----
  const clockNodeTL = T(self => {
    const clockTL = T(self => {
      const f = () =>
        self.now = new Date().toLocaleTimeString();
      setInterval(f, 1000);
    });
    const timeline = clockTL.sync(clock =>
      self.now = <div>{clock}</div>
    );

    world.now = clockTL;
  });

  const counterNodeTL = T(self => {
    const countTL = T(self => self.now = 0);
    const timeline = countTL.sync(count =>
      self.now = (<div>
        <p>You clicked {count} times</p>
        <button onclick={() => countTL.now = count + 1}>
          Click me
        </button>
      </div>)
    );
    world.now = countTL;
  });

  const mergeTL = (TLs => T(self =>
    TLs.map(TL => TL.sync(() =>
      self.now = TLs.map(TL => TL.now)
    ))
  ))([clockNodeTL, counterNodeTL]);

  const topNodeTL = T(self =>
    mergeTL.sync(([clockNode, counterNode]) =>
      self.now = <div>
        <h3>{clockNode}</h3>
        {counterNode}
      </div>
    )
  );

  const viewNodeTL = topNodeTL.sync(
    node => patch(document.getElementById("app"), node)
  );

  world.now = topNodeTL;
  world.now = mergeTL;
  world.now = clockNodeTL;
  world.now = counterNodeTL;
----

[NOTE] 
.Everything mutable is described as __timeline__ 
====
All of the global variables are __timeline__ of Node (virtualDOM) except the `mergeTL` definitoin
==== 

++++
<iframe height="312" style="width: 100%;" scrolling="no" title="unlimitedjs mirge timelines of clock &amp; counter node" src="https://codepen.io/stken2050/embed/WPzMNK/?height=312&theme-id=36003&default-tab=js,result" frameborder="no" allowtransparency="true" allowfullscreen="true">
  See the Pen <a href='https://codepen.io/stken2050/pen/WPzMNK/'>unlimitedjs mirge timelines of clock &amp; counter node</a> by Ken OKABE
  (<a href='https://codepen.io/stken2050'>@stken2050</a>) on <a href='https://codepen.io'>CodePen</a>.
</iframe>
++++