= Material Design Components for web
ifndef::stem[:stem: latexmath]
ifndef::imagesdir[:imagesdir: ./img/]
ifndef::source-highlighter[:source-highlighter: highlightjs]
ifndef::highlightjs-theme:[:highlightjs-theme: solarized-dark]

[[topcode]]
== unlimitedjs works with Material Design Components(MDC) for web

Material Design Components for the web (MDC Web) offers designers and developers a way to implement Material Design in their websites. Developed by a core team of engineers and UX designers at Google, these components enable a reliable development workflow to build beautiful and functional web projects.

https://material.io/design/

There are two ways to include MDC Web: either by adding a few lines of code and instantiating the JavaScript file or by using MDC Web as Node modules, bundling the Sass and JavaScript yourself using something like webpack.

https://github.com/material-components/material-components-web/blob/master/docs/getting-started.md

== Hello MDC with unlimitedjs

++++
<iframe height="469" style="width: 100%;" scrolling="no" title="unlimitedjs + MDC hello" src="https://codepen.io/stken2050/embed/eXOgoO/?height=469&theme-id=36003&default-tab=js,result" frameborder="no" allowtransparency="true" allowfullscreen="true">
  See the Pen <a href='https://codepen.io/stken2050/pen/eXOgoO/'>unlimitedjs + MDC hello</a> by Ken OKABE
  (<a href='https://codepen.io/stken2050'>@stken2050</a>) on <a href='https://codepen.io'>CodePen</a>.
</iframe>
++++

[source, html]
.Hello.html
----
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8" />
    <link href="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css" rel="stylesheet">
    <script src="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.js"></script>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

    <script type="module" src="./unlimitedjs-materialdesign/build/hello.js"></script>

</head>

<body>
    <div id="app"></div>
</body>

</html>
----

[source,js]
.hello.tsx
----
import { T, world } from "../../lib/timeline-monad/code/dist/timeline-monad.js";
import { h, patch } from "../../lib/superfine/src/index.js";

const topNodeTL = T(self =>
  self.now =
  <button class="mdc-button mdc-button--raised"> <1>
    Press Me
    </button>
);

const viewNodeTL = topNodeTL.sync(node => <2>
  patch(document.getElementById("app"), node)
);

const mdcTL = viewNodeTL.sync(() => {  <3>
  Array.from(document
    .querySelectorAll('.mdc-button'))  <4>
    .map(button =>
      (window as any).mdc.ripple
        .MDCRipple.attachTo(button));
});

world.now = topNodeTL; <5>
----

<1> MDC button class specifiers
<2> Render pattern of unlimitedjs
<3> mdcTL is a timeline that is synchronized to the viewNodeTL that is virtualDOM rendering timeline 
<4> The standard manner to attach JavaScript to MDC, see https://github.com/material-components/material-components-web/tree/master/packages/mdc-ripple[the document] and https://github.com/material-components/material-components-web/issues/3236[the issue]

<5> Initialize `topNodeTL`
 