= Material Design Components for web
ifndef::stem[:stem: latexmath]
ifndef::imagesdir[:imagesdir: ./img/]
ifndef::source-highlighter[:source-highlighter: highlightjs]
ifndef::highlightjs-theme:[:highlightjs-theme: solarized-dark]

[[topcode]]
== unlimitedjs works with Material Design Components(MDC) for web

Material Design Components for the web (MDC Web) offers designers and developers a way to implement Material Design in their websites. Developed by a core team of engineers and UX designers at Google, these components enable a reliable development workflow to build beautiful and functional web projects.

https://material.io/design/

MDC web is the successor to Material Design Lite, and in this article we are going to go through a basic set up of how to use MDC web.

There are two ways to include MDC Web: either by adding a few lines of code and instantiating the JavaScript file or by using MDC Web as Node modules, bundling the Sass and JavaScript yourself using something like webpack.

https://github.com/material-components/material-components-web/blob/master/docs/getting-started.md

== Hello MDC
 