= Material Design Components for web
ifndef::stem[:stem: latexmath]
ifndef::imagesdir[:imagesdir: ./img/]
ifndef::source-highlighter[:source-highlighter: highlightjs]
ifndef::highlightjs-theme:[:highlightjs-theme: solarized-dark]

[[topcode]]
== unlimitedjs works with Material Design Components(MDC) for web

Material Design Components for the web (MDC Web) offers designers and developers a way to implement Material Design in their websites. Developed by a core team of engineers and UX designers at Google, these components enable a reliable development workflow to build beautiful and functional web projects.

https://material.io/design/

MDC web is the successor to Material Design Lite, and in this article we are going to go through a basic set up of how to use MDC web.

There are two ways to include MDC Web: either by adding a few lines of code and instantiating the JavaScript file or by using MDC Web as Node modules, bundling the Sass and JavaScript yourself using something like webpack.

https://github.com/material-components/material-components-web/blob/master/docs/getting-started.md

== Hello MDC

[source,js]
.Hello unlimitedjs+MDC
----
import { T } from "../../node_modules/timeline-monad/dist/esm/timeline-monad.js";
import { h, patch } from "../../node_modules/superfine/src/index.js";

const main = () => {

  const messageTL = T(self =>
    setTimeout(() => (self.now = ""), 0)
  );

  const outputNodeTL = (messageTL =>
    T(self =>
      messageTL.sync(message =>
        self.now = <h3 mdc-typography--headline3>
        {message}</h3>
      )
    )
  )(messageTL);

  const inputNode = (messageTL => {
    const firstTL = T();
    const lastTL = T();
    const btnTL = T(self =>
      self.sync(() =>
        messageTL.now =
        firstTL.now === undefined
          || lastTL.now === undefined
          ? undefined
          : "Welcome " +
          firstTL.now + " " + lastTL.now
      )
    );

    //===
    return <div>

    <h2 class="mdc-typography--headline2">
      Hello, unlimitedjs!</h2>

    <div class="mdc-text-field">
      <input type="text" id="first-name"
        class="mdc-text-field__input" 
        onchange = {e=> 
          firstTL.now = e.currentTarget.value}/>
      <label class="mdc-floating-label"
        for="first-name">First name</label>
      <div class="mdc-line-ripple"></div>
    </div>

    <br/>

    <div class="mdc-text-field">
      <input type="text" id="last-name"
        class="mdc-text-field__input" 
        onchange = {e=> 
          lastTL.now = e.currentTarget.value}/>
      <label class="mdc-floating-label"
        for="last-name">Last name</label>
      <div class="mdc-line-ripple"></div>
    </div>

    <br/>
    
    <button type="button" class="mdc-button 
    mdc-button--raised mdc-button--primary"
    onclick = {()=> btnTL.now = true} >
      Press Me</button>

    </div>;
    //===
  })(messageTL);

  const topNodeTL = outputNodeTL.sync(outputNode =>
    <div>
      {inputNode}
      {outputNode}
    </div>
  );

  const viewNodeTL = topNodeTL.sync(topNode =>
    patch(viewNodeTL.now, topNode, document.body)
  );

  const mdcTL = viewNodeTL.sync(() => {

    Array.from(document
      .querySelectorAll('.mdc-text-field'))
      .map(textField =>
        (window as any).mdc.textField
          .MDCTextField.attachTo(textField));

    Array.from(document
      .querySelectorAll('.mdc-button'))
      .map(button =>
        (window as any).mdc.ripple
          .MDCRipple.attachTo(button));

  });

};

export { main };
----

++++
<iframe height="707" style="width: 100%;" scrolling="no" title="unlimitedjs + MDC hello" src="//codepen.io/stken2050/embed/vbjzBP/?height=707&theme-id=36003&default-tab=js,result" frameborder="no" allowtransparency="true" allowfullscreen="true">
  See the Pen <a href='https://codepen.io/stken2050/pen/vbjzBP/'>unlimitedjs + MDC hello</a> by Ken OKABE
  (<a href='https://codepen.io/stken2050'>@stken2050</a>) on <a href='https://codepen.io'>CodePen</a>.
</iframe>
++++